/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
// package GUI;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.awt.Font;

import GUI.*;
/**
 *
 * @author Admin
 */
public class Main_layout extends javax.swing.JFrame {

    /**
     * Creates new form Main_layout
     */
    private javax.swing.JLabel currentUser_label;

    public Main_layout() {
        this("");
    }

    public Main_layout(String username) {
        initComponents();
        setTitle("Quản lý cửa hàng bán xe máy");
        jPanel1.setBackground(new Color(70,20,180));
        jPanel2.setBackground(new Color(70,130,180));
        
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/IMG/logo.png"));
        Image logo = icon1.getImage().getScaledInstance(230,100, Image.SCALE_SMOOTH);
        jLabel2.setIcon(new ImageIcon(logo));
        
        chucNang_label.setFont(new Font("Arial", Font.BOLD, 16));
        chucNang_label.setForeground(Color.white);
 
        currentUser_label = new javax.swing.JLabel();
        currentUser_label.setFont(new Font("Arial", Font.ITALIC, 14));
        currentUser_label.setForeground(Color.white);
        currentUser_label.setText("Người dùng hiện tại: " + username);
        jPanel1.add(currentUser_label);
        currentUser_label.setBounds(banHang_btn.getX(), chucNang_label.getY() + 25, 200, 20);
 
        // Custom button styles
        Font buttonFont = new Font("Segoe UI", Font.BOLD, 14);
        Color buttonBackground = new Color(100, 149, 237); 
        Color buttonForeground = Color.WHITE;
 
        javax.swing.JButton[] buttons = {
            banHang_btn, qlnv_btn, qlsp_btn, qlkh_btn, qltk_btn, nhapHang_btn, dangXuat_btn, thongKe_btn
        };
 
        for (javax.swing.JButton btn : buttons) {
            btn.setFont(buttonFont);
            btn.setBackground(buttonBackground);
            btn.setForeground(buttonForeground);
            btn.setFocusPainted(false);
            btn.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(65, 105, 225), 2)); // Royal Blue border
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        banHang_btn = new javax.swing.JButton();
        qlnv_btn = new javax.swing.JButton();
        qlsp_btn = new javax.swing.JButton();
        qlkh_btn = new javax.swing.JButton();
        qltk_btn = new javax.swing.JButton();
        nhapHang_btn = new javax.swing.JButton();
        chucNang_label = new javax.swing.JLabel();
        dangXuat_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        thongKe_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        banHang_btn.setText("Bán hàng");

        qlnv_btn.setText("Quản lý nhân viên ");
        qlnv_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlnv_btnActionPerformed(evt);
            }
        });

        qlsp_btn.setText("Quản lý sản phẩm");
        qlsp_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlsp_btnActionPerformed(evt);
            }
        });

        qlkh_btn.setText("Quản lý khách hàng");
        qlkh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlkh_btnActionPerformed(evt);
            }
        });

        qltk_btn.setText("Quản lý tài khoản");
        qltk_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qltk_btnActionPerformed(evt);
            }
        });

        nhapHang_btn.setText("Nhập hàng");
        nhapHang_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhapHang_btnActionPerformed(evt);
            }
        });

        chucNang_label.setText("Chức năng");

        dangXuat_btn.setText("Đăng xuất");

        thongKe_btn.setText("Thống kê");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(dangXuat_btn)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(chucNang_label)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(banHang_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(qlnv_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(qlsp_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(qlkh_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(qltk_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nhapHang_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(thongKe_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(chucNang_label)
                .addGap(32, 32, 32)
                .addComponent(banHang_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(qlnv_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(qlsp_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(qlkh_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(qltk_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nhapHang_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(thongKe_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(dangXuat_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 918, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void qlsp_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlsp_btnActionPerformed
        // TODO add your handling code here:
            QuanLySanPham_GUI qlsp = new QuanLySanPham_GUI();
            qlsp.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_qlsp_btnActionPerformed

    private void qlkh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlkh_btnActionPerformed
        QuanLyKhachHang_GUI qlkh = new QuanLyKhachHang_GUI();
        qlkh.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_qlkh_btnActionPerformed

    private void qltk_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qltk_btnActionPerformed
        // TODO add your handling code here:
        // GUIQuanLyTaiKhoan tk = new GUIQuanLyTaiKhoan();
        // tk.setVisible(true);
        // this.dispose();
    }//GEN-LAST:event_qltk_btnActionPerformed

    private void nhapHang_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhapHang_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nhapHang_btnActionPerformed

    private void thongKe_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhapHang_btnActionPerformed
        // TODO add your handling code here:
        // GUIDangNhap dangNhap = new GUIDangNhap();
        // dangNhap.setVisible(true);
        // this.dispose();
    }//GEN-LAST:event_nhapHang_btnActionPerformed

    private void qlnv_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlnv_btnActionPerformed
        QuanLyNhanVien_GUI qlnv = new QuanLyNhanVien_GUI();
        qlnv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_qlnv_btnActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_layout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton banHang_btn;
    private javax.swing.JLabel chucNang_label;
    private javax.swing.JButton dangXuat_btn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton nhapHang_btn;
    private javax.swing.JButton qlkh_btn;
    private javax.swing.JButton qlnv_btn;
    private javax.swing.JButton qlsp_btn;
    private javax.swing.JButton qltk_btn;
    private javax.swing.JButton thongKe_btn;
    // End of variables declaration//GEN-END:variables
}
